server:
  port: 8080
spring:
  data:
    mongodb:
      uri: ${MONGO_URI}
      database: "franchises"
  application:
    name: "Franquicias"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
  health:
    circuitbreakers:
      enabled: true

resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 30s
        failureRateThreshold: 50
        slowCallRateThreshold: 50
        slowCallDurationThreshold: 2s
        automaticTransitionFromOpenToHalfOpenEnabled: true
    instances:
      mongoDb:
        baseConfig: default

adapters:
  mongo:
    resilience:
      circuit-breaker-name: mongoDb
      timeout-in-ms: 3000

cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"

routers:
  paths:
    franchises: "/api/v1/franquicias"
    branches: "/api/v1/sucursales"
    products: "/api/v1/productos"
    productsUpdateStock: "/api/v1/productos/update-stock"
    topProducts: "/api/v1/franchises/{franchiseName}/top-products-per-branch"
