server:
  port: 8080
spring:
  data:
    mongodb:
      uri: "mongodb+srv://andresganan_db_user:N5FUTWAPrIfTzklH@anfega.ybqhqud.mongodb.net/?retryWrites=true&w=majority&appName=anfega"
      database: "franchises"
  application:
    name: "Franquicias"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"

routers:
  paths:
    franchises: "/api/v1/franquicias"
    branches: "/api/v1/sucursales"
