services:
  app-service:
    build:
      context: ..
      dockerfile: deployment/Dockerfile
    image: franquicias-app:latest
    container_name: franquicias-app
    ports:
      - "8080:8080"
    restart: unless-stopped
